# Generated by Django 2.1.1 on 2018-10-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0002_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('specializations', models.CharField(max_length=256)),
                ('short_description', models.TextField()),
                ('medical_condition', models.TextField()),
                ('treatement_description', models.TextField()),
                ('related_symptoms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.PositiveIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='symptoms',
            name='issues_id',
            field=models.CharField(default=-1, max_length=256),
            preserve_default=False,
        ),
    ]
