# Generated by Django 2.1.1 on 2018-10-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0004_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='year_of_birth',
            new_name='yearofbirth',
        ),
    ]
