# Generated by Django 2.1.1 on 2018-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0005_auto_20181014_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.TextField(default='male'),
            preserve_default=False,
        ),
    ]
