# Generated by Django 2.1.1 on 2018-10-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0006_details_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
